export const ADD_TEXT = "ADD_TEXT";
export const DELETE_TEXT = "DELETE_TEXT";
export const MOVE_TEXT = "MOVE_TEXT";
export const RESIZE_TEXT = "RESIZE_TEXT";

export const ADD_LOGO = "ADD_LOGO";
export const DELETE_LOGO = "DELETE_LOGO";
export const MOVE_LOGO = "MOVE_LOGO";
export const RESIZE_LOGO = "RESIZE_LOGO";


export const REMOVE_BACKGROUND = "REMOVE_BACKGROUND";

export const LOAD_BACKGROUNDS = "LOAD_BACKGROUNDS";
export const LOAD_LOGOS = "LOAD_LOGOS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAILED = "SIGN_IN_USER_FAILED";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const SIGN_IN_PROGRESS = "SIGN_IN_PROGRESS";

export const COLOR_CHANGE = "COLOR_CHANGE";
export const SELECT_TOOL = "SELECT_TOOL";


export const SAVE_LOGO_SUCCESS = "SAVE_LOGO_SUCCESS";
export const SAVE_LOGO_FAILED = "SAVE_LOGO_FAILED";

export const SAVE_BACKGROUND_SUCCESS = "SAVE_BACKGROUND_SUCCESS";
export const SAVE_BACKGROUND_FAILED = "SAVE_BACKGROUND_FAILED";
export const ADD_BACKGROUND = "ADD_BACKGROUND";
export const DELETE_BACKGROUND = "DELETE_BACKGROUND";

export const SAVE_IMAGE_SUCCESS = "SAVE_IMAGE_SUCCESS";
export const SAVE_IMAGE_FAILED = "SAVE_IMAGE_FAILED";

export const SAVE_IMAGES_SUCCESS = "SAVE_IMAGES_SUCCESS";
export const SAVE_IMAGES_FAILED = "SAVE_IMAGES_FAILED";

export const SAVE_IMAGE_LOGOS_SUCCESS = "SAVE_IMAGE_LOGOS_SUCCESS";
export const SAVE_IMAGE_LOGOS_FAILED = "SAVE_IMAGE_LOGOS_FAILED";

export const SAVE_IMAGE_BACKGROUNDS_REMOTE = "SAVE_IMAGE_BACKGROUNDS_REMOTE";
export const SAVE_IMAGE_LOGOS_REMOTE = "SAVE_IMAGE_LOGOS_REMOTE";

export const SAVE_IMAGE_BACKGROUNDS_SUCCESS = "SAVE_IMAGE_BACKGROUNDS_SUCCESS";
export const SAVE_IMAGE_BACKGROUNDS_FAILED = "SAVE_IMAGE_BACKGROUNDS_FAILED";

export const SELECTED_BACKGROUND = "SELECTED_BACKGROUND";