export const ADD_TEXT = "ADD_TEXT";
export const DELETE_TEXT = "DELETE_TEXT";
export const MOVE_TEXT = "MOVE_TEXT";
export const RESIZE_TEXT = "RESIZE_TEXT";

export const ADD_LOGO = "ADD_LOGO";
export const DELETE_LOGO = "DELETE_LOGO";
export const MOVE_LOGO = "MOVE_LOGO";
export const RESIZE_LOGO = "RESIZE_LOGO";

export const ADD_BACKGROUND = "ADD_BACKGROUND";
export const REMOVE_BACKGROUND = "REMOVE_BACKGROUND";

export const LOAD_BACKGROUNDS = "LOAD_BACKGROUNDS";
export const LOAD_LOGOS = "LOAD_LOGOS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAILED = "SIGN_IN_USER_FAILED";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const SIGN_IN_PROGRESS = "SIGN_IN_PROGRESS";